#!/bin/bash

#두 개의 사용자(steam 및 pzuser)를 추가(암호root) / SUDOER
#echo와 tee 명령어를 사용하여 /etc/sudoers 파일에 새 규칙을 추가

# 사용자 'steam' 추가 및 패스워드 설정
sudo useradd -m steam
echo "steam:root" | sudo chpasswd

# 'steam' 사용자에게 sudo 권한 부여
echo "steam ALL=(ALL:ALL) ALL" | sudo tee -a /etc/sudoers

# 사용자 'pzuser' 추가 및 패스워드 설정
sudo useradd -m pzuser
echo "pzuser:root" | sudo chpasswd

# 'pzuser' 사용자에게 sudo 권한 부여
echo "pzuser ALL=(ALL:ALL) ALL" | sudo tee -a /etc/sudoers
