#!/bin/bash

# 사용자 추가 및 패스워드 설정
sudo useradd -m steam
echo "root" | sudo passwd steam --stdin
echo "root" | sudo passwd --stdin

# /etc/apt/sources.list 파일 편집
sed -i 's/$/ contrib non-free/' /etc/apt/sources.list

# /etc/sudoers 파일 편집
echo "steam	ALL=(ALL:ALL) ALL" | sudo tee -a /etc/sudoers
echo "pzuser	ALL=(ALL:ALL) ALL" | sudo tee -a /etc/sudoers

# 필요한 패키지 설치
sudo -u steam -s
cd /home/steam
sudo apt install software-properties-common -y
sudo dpkg --add-architecture i386
sudo apt update
sudo apt install lib32gcc-s1 steamcmd -y

# steamcmd 설치
sudo ln -s /usr/games/steamcmd /home/steam/steamcmd
